// packages/solid/src/index.ts
import {
  createContext,
  createSignal,
  onCleanup,
  useContext,
  type Accessor,
  type Context,
  type JSX,
} from "solid-js";

import { CosystemError, type App, type InjectionToken } from "@cosystem/core";

export interface CoSystemProviderProps {
  readonly app: App;
  readonly children?: JSX.Element;
}

export interface UseComputedOptions<T> {
  readonly equals?: (value: T, previous: T) => boolean;
}

export type AppSelector<T> = (app: App) => T;
export type ModuleSelector<TModule, TValue> = (module: TModule, app: App) => TValue;

export const CoSystemContext: Context<App | undefined> = createContext<App>();

export function CoSystemProvider(props: CoSystemProviderProps): JSX.Element {
  return CoSystemContext.Provider({
    get children() {
      return props.children;
    },
    value: props.app,
  });
}

export function useApp(): App {
  const app = useContext(CoSystemContext);

  if (app === undefined) {
    throw new CosystemError("Missing Solid CoSystemProvider.");
  }

  return app;
}

export function useModule<T>(token: InjectionToken<T>): T {
  return useApp().getModule(token);
}

export function useComputed<T>(
  selector: AppSelector<T>,
  options?: UseComputedOptions<T>,
): Accessor<T>;
export function useComputed<TModule, TValue>(
  token: InjectionToken<TModule>,
  selector: ModuleSelector<TModule, TValue>,
  options?: UseComputedOptions<TValue>,
): Accessor<TValue>;
export function useComputed<TModule, TValue>(
  first: AppSelector<TValue> | InjectionToken<TModule>,
  second?: ModuleSelector<TModule, TValue> | UseComputedOptions<TValue>,
  third?: UseComputedOptions<TValue>,
): Accessor<TValue> {
  const app = useApp();
  const selector =
    typeof second === "function"
      ? (currentApp: App) =>
          second(currentApp.getModule(first as InjectionToken<TModule>), currentApp)
      : (first as AppSelector<TValue>);
  const options = typeof second === "function" ? third : second;
  const equals = options?.equals ?? Object.is;
  const [value, setValue] = createSignal(selector(app), { equals });
  const unsubscribe = app.watch(
    () => selector(app),
    (next) => {
      setValue(() => next);
    },
    { equals },
  );

  onCleanup(unsubscribe);

  return value;
}

// packages/angular/src/index.ts
import {
  DestroyRef,
  InjectionToken,
  inject,
  makeEnvironmentProviders,
  signal,
  type EnvironmentProviders,
  type Signal,
} from "@angular/core";

import { type App, type InjectionToken as CoSystemToken } from "@cosystem/core";

export interface InjectSignalOptions<T> {
  readonly equals?: (value: T, previous: T) => boolean;
}

export type AppSelector<T> = (app: App) => T;
export type ModuleSelector<TModule, TValue> = (module: TModule, app: App) => TValue;

export const COSYSTEM_APP: InjectionToken<App> = new InjectionToken<App>("CoSystem App");

export function provideCoSystem(app: App): EnvironmentProviders {
  return makeEnvironmentProviders([
    {
      provide: COSYSTEM_APP,
      useValue: app,
    },
  ]);
}

export function injectCoSystemApp(): App {
  return inject(COSYSTEM_APP);
}

export function injectModule<T>(token: CoSystemToken<T>): T {
  return injectCoSystemApp().getModule(token);
}

export function injectSignal<T>(
  selector: AppSelector<T>,
  options?: InjectSignalOptions<T>,
): Signal<T>;
export function injectSignal<TModule, TValue>(
  token: CoSystemToken<TModule>,
  selector: ModuleSelector<TModule, TValue>,
  options?: InjectSignalOptions<TValue>,
): Signal<TValue>;
export function injectSignal<TModule, TValue>(
  first: AppSelector<TValue> | CoSystemToken<TModule>,
  second?: ModuleSelector<TModule, TValue> | InjectSignalOptions<TValue>,
  third?: InjectSignalOptions<TValue>,
): Signal<TValue> {
  const app = injectCoSystemApp();
  const destroyRef = inject(DestroyRef);
  const selector =
    typeof second === "function"
      ? (currentApp: App) =>
          second(currentApp.getModule(first as CoSystemToken<TModule>), currentApp)
      : (first as AppSelector<TValue>);
  const options = typeof second === "function" ? third : second;
  const equals = options?.equals ?? Object.is;
  const value = signal(selector(app), { equal: equals });
  const unsubscribe = app.watch(
    () => selector(app),
    (next) => {
      value.set(next);
    },
    { equals },
  );

  destroyRef.onDestroy(unsubscribe);

  return value.asReadonly();
}
